[package]
name = "timers"
version = "1.0.1"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
clap = { version = "4.5.23", features = ["derive"] }
crossbeam-channel = "0.5.14"
figlet-rs = "0.1.5"
ratatui = "0.29.0"
soloud = "1.0.5"
